export { default as Home } from './Home'
export { default as About } from './About'
export { default as NoPage } from './NoPage'
export { default as Projects } from './Projects'
export { default as Resume } from './Resume'